# -*- coding: utf-8 -*-
"""MOCK_PRACTICAL.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ayVHc9H95OEv-7AqToXQgBmGis4FN4UL
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
import matplotlib.pyplot as plt

df=pd.read_csv('Salary_Data.csv')

df.head()

df.shape

df.isnull().sum()

df.describe()

X = df.drop(['Salary'], axis=1)
y = df['Salary']

X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.6, random_state=42)

reg=LinearRegression()

reg.fit(X_train, y_train)

y_pred=reg.predict(X_test)

print(f"Intercept {reg.intercept_}")
print(f"Coefficient {reg.coef_}")

rscore=r2_score(y_test, y_pred)
print(rscore)

c = [i for i in range (1,len(y_test)+1, 1)]
c

y_test

plt.plot(c, y_test, color="r")
plt.plot(c, y_pred, color="c")
plt.xlabel("Index")
plt.ylabel("Salary Prediction")
plt.legend(['original salary', 'predicted salary'])
plt.show()